### ISSUE TITLE
Game Of Life would be awesome!

### ISSUE THREAD

**Issue by ComFreek** [shinh/elvm#60]
Some really awesome people implemented a whole CPU in Game of Life together with a Tetris implementation in a [custom programming language, a custom assembly language and a custom assembler!
See [Build a working game of Tetris in Conway's Game of Life on CodeGolf.SE](https://codegolf.stackexchange.com/q/11880/4040).

Their [language](https://codegolf.stackexchange.com/a/142683/4040) seems quite sophisticated, hence an ELVM backend shouldn't be too hard :smile:

**Comment by shinh** [comment]
Yeah, I'm very interested in it, too. I thought some one in the stackexchage was actually working for it, but I don't know their status.

**Comment by woodrush** [comment]
I created an ELVM backend for QFTASM, the assembly language used in The Quest for Tetris project which is available [here](https://github.com/woodrush/elvm/tree/master/tools/qftasm). Since the [QFTASM interpreter](https://github.com/QuestForTetris/qftasm-interpreter) and the [meta-Game of Life (Varlife) simulator](https://github.com/QuestForTetris/variations-of-life) are licensed under the MIT License, and since my forked repo only contains assembly-related code and not the actual Game of Life patterns, I think it's OK to create a pull request, but since the repo containing the final Game of Life pattern didn't have a license associated with it, I'm currently asking the original authors of QFTASM to make sure I could issue a PR.

**Comment by shinh** [comment]
Exciting! Can we actually feed QFTASM compiled from simple C programs to actual lifegame simulator and see the animation? As for PUTC, I'm wondering if we can implement a terminal device on lifegame. It'd be cool if PUTC reads a value from RAM, somehow sends a bunch of gliders to the terminal device, and the terminal device shows texts with prebuilt font. I don't know the stack of quest for tetris and it's plausible, though.

**Comment by woodrush** [comment]
Thanks! :) As for the video, definitely! I was able to run [this very short calculator program](https://github.com/woodrush/elvm/blob/add-qftasm/tools/qftasm/add.c) on an actual Game of Life (GoL) system using [Golly](https://en.wikipedia.org/wiki/Golly_(program)), so we could definitely make a video. (I'm working on making [this more sophisticated calculator program](https://github.com/woodrush/elvm/blob/add-qftasm/tools/qftasm/calc.c) run on GoL as well.)

As for making a display for PUTC, it's actually already kind of possible. Since the RAM states are visually recognizable and also aligned on a grid, we can visualize binary bitmaps by writing the bitmap data directly into the RAM, as the original authors of QFT did when visualizing the Tetris board. The results look like this: (The pattern below is a modified version of [this pattern](https://github.com/QuestForTetris/QFT/blob/master/Tetris8.mc) converted from Varlife to GoL, rendered on Golly. Each "pixel" here is actually a 2048x2048 GoL pattern.)
![image](https://user-images.githubusercontent.com/4700588/114250952-569d4600-99da-11eb-8aa5-2b0d780af2f8.png) 
This image shows the RAM showing an ascii string "150" (read backwards from the bottom - it's the output of my calculator program), but we can make program show bitmaps like in this image as well. Although the pixels are quite small, I think it's at least quite recognizable. I have a vague idea of making the pixels to be shown larger, but that would be a separate project.

I also have some updates on the License for QFT. Two of the authors of QFT have given a kind and quick response in [this issue](https://github.com/QuestForTetris/tetris-writeup/issues/8), and also have made a [pull request](https://github.com/QuestForTetris/QFT/pull/12) to add the MIT License to QFT's main repo as well. I'll be waiting a little bit until this PR is merged, so that we can be 100% comfortable about the license.

----

Some more details on running programs. The GoL pattern for the QFT computer is created by systematically converting a pattern created on a different cellular automaton rule called Varlife to GoL. Golly is able to directly run Varlife patterns as well, and I was able to run the [more sophisticated calculator program](https://github.com/woodrush/elvm/blob/add-qftasm/tools/qftasm/calc.c) that I mentioned earlier on Varlife in about 2 minutes, which I think is pretty short.
The ELVM backend is already extensively tested on Varlife. I'm now experimenting on running everything on the GoL layer, which was a little bit complicated than I first expected, but is overall going well. Some very short programs run in a couple of minutes on GoL, but others take hours long. I'm now working on making the more sophisticated calculator program work on GoL, since I believe it would be more interesting since the program uses richer features of C.
Also, since I found some minor bugs when running programs on the GoL layer, I'm currently brushing up my ELVM fork to make it GoL-compatible.

**Comment by elendiastarman** [comment]
Hi! :wave: I'm one of the authors of QFT. I went ahead and merged the license PR since there hasn't been any activity or discussion (most team members are off doing their own thing, naturally). It's super cool to see y'all building on it! Let me know if I need to add licenses to other repos - I noticed a couple but they're not core repos so I don't think it'll be a problem.

**Comment by woodrush** [comment]
Thank you very much! Yeah, the QFT computer is so full of cool ideas, it's exciting to analyze and work on too! Thanks too for your support, I believe we're now all set with the licenses too. I'll let you know when I make the pull request here once I finish brushing up my repo.

**Comment by shinh** [comment]
Thanks for the detailed description. All sound awesome! I'll find some time to try it out.

**Comment by woodrush** [comment]
Thanks! Please ask me if you have any questions about the forked repo.
I think I'll be able to get my pull request ready tomorrow or the day after tomorrow. I'm doing some final checks on the actual Game of Life system now.

**Comment by woodrush** [comment]
I'm very sorry for the large delay. To make sure that the layer for porting the QFTASM code to Game of Life is working properly, I was working on [QFT-devkit](https://github.com/woodrush/QFT-devkit) and [lisp-in-life](https://github.com/woodrush/lisp-in-life), which took more time than expected. I'm also sorry that I didn't notice your pull request in my branch - the email notifications from GitHub was not working. I commented on your pull request at https://github.com/woodrush/elvm/pull/1 .

I've finally created #103 which adds the QFTASM backend. I've revised the readme so that the most important information such as the required packages, compilation and testing are explained shortly.

I've also created another project, [QFT-devkit](https://github.com/woodrush/QFT-devkit), so that QFTASM code can be ported to an actual Game of Life (and Varlife) pattern. Since the tests in the actual Game of Life environment cannot be run in the terminal, and it also takes a lot of time, I thought it made sense to separate this as a different project.

I also made a derivative project, [lisp-in-life](https://github.com/woodrush/lisp-in-life). As a Lisp fan, I wanted to port Lisp to GoL. Since I hadn't written C that much before, I referenced some techniques such as linked lists from [lisp.c](https://github.com/shinh/elvm/blob/master/test/lisp.c) from ELVM, but otherwise I wrote the interpreter code from scratch. Since the Lisp pattern is working on Golly, I believe that the ELVM-QFT-devkit toolchain is working properly.

Also pinging to @elendiastarman !

**Comment by shinh** [comment]
Thanks for the PR! I'd like to mention it in README.md:  https://github.com/shinh/elvm/pull/104

**Comment by shinh** [comment]
Yeah, I was wondering if we can port Lisp interpreter to QFTASM after I learned 24bit programs like 8cc is not supported. Thanks again for the great work. I wanted game of life backend for ~5 years, but I haven't expected it'll be real!

**Comment by woodrush** [comment]
Thanks for the merge and the mention in README.md!

As a large fan of esoteric languages and esoteric use of languages (I write things like [this](https://blogs.mathworks.com/pick/2014/12/12/obfuscated-matlab-code/)), it was very fun for me to learn about and work on ELVM too. It was so exciting for me too to see C and lisp running on the Game of Life. Thanks to you too for such an inspiring work!

**Comment by shinh** [comment]
The trees look great!

**Comment by ComFreek** [comment]
Wohoo, almost two years after I have jokingly opened this issue, this has become real!
@woodrush Excellent work!

Are there any pictures (or even a video?) of a demo program running through the ELVM chain with the Game of Life backend? I think this would be a worthy addition in the README.

**Comment by woodrush** [comment]
Thanks! I made a separate project, [lisp-in-life](https://github.com/woodrush/lisp-in-life), where I put some videos and images. I'll be putting videos and images on that repo.
