### ISSUE TITLE
Volatile Semantics

### ISSUE THREAD

**Issue by DarthRubik** [shinh/elvm#67]
Greetings.....so as far as I can tell, this compiler doesn't encode volatile semantics in the IR....(maybe I am mistaken...if so let me know).

So I guess ultimately the problem is this:

`
volatile unsigned char x;
void foo()
{
  while (x != 12){}
}
`
The c backend would generate something equivalent to this:

`
unsigned char x;
void foo()
{
  while (x != 12){}
}
`

And then the compiler that you feed this into (which could be an optimizing compiler) will say....oops x is never changed, so I am going to just optimize out all but the first check on the loop (https://godbolt.org/z/CXsSfg)

Anyways.....let me what are your plans are in this regard? (A legitimate response can be that is outside scope.....)

**Comment by shinh** [comment]
Compilers can handle volatile variables by generating code which always read values from memory to registers instead of reusing values loaded to registers. Actually, 8cc does no optimization/register allocation and all variables are treated as volatile.

Introducing volatile to the IR would make sense if we have optimization pass after generating the IR. However, we don't have such yet and I think the IR isn't a good representation for further optimization (unlike LLVM IR, EIR is not SSA)
