### ISSUE TITLE
bootstraping with ELVM and 8cc.

### ISSUE THREAD

**Issue by keito940** [shinh/elvm#69]
Sorry for the practical story. 
Is it possible to bootstrap 8cc with ELVM and build a compiler structure with 8cc based on ELVM?

**Comment by shinh** [comment]
Yes, of course. I checked sanity of the toolchain by the following steps

1. build 8cc by gcc (target=elvm host=x86)
2. build elc by gcc (host=x86)
3. build 8cc.bf by 1 and 2
4. build elc.bf by 1 and 2
5. build 8cc.bf again by 3 and 4
6. build elc.bf again by 3 and 4
7. compare 3 vs 5 and 4 vs 6, since there were no diff, we can iterate these steps forever

This script does it:

https://github.com/shinh/elvm/blob/master/tools/check_selfhost.sh

It took ~100 hours when I ran this for bf target.

http://shinh.skr.jp/slide/elvm/self_host2.svg
